language: python
python:
   - "2.7"
   - "3.3"
   - "3.4"
env:
  - PD=0.14
  - PD=0.13.1
  - PD=0.13
before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran gcc
# See http://conda.pydata.org/docs/travis.html
install:
  # You may want to periodically update this, although the conda update
  # conda line below will keep everything up-to-date.
  # This saves us some downloading for this version
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Should match requirements.txt
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas=$PD matplotlib
  - source activate test-environment
  # Build in place so we can run tests
  - python setup.py build_ext --inplace
# command to run tests
script: python -m lifelines.tests.test_suite
# Don't want notifications
notifications:
  email: false
