language: python
python:
   - "2.7"
   - "3.4"
before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran gcc
# See http://conda.pydata.org/docs/travis.html
install:
  # You may want to periodically update this, although the conda update
  # conda line below will keep everything up-to-date.
  # This saves us some downloading for this version
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda install conda-build jinja2 setuptools pip patchelf
  # Build the conda package
  - conda build .
  # Install the package
  - conda install lifelines --use-local
# What to run
script: python -c "from lifelines.statistics import concordance_index"
# Don't want notifications
notifications:
  email: false
